import { Code, Cpu, Database, Globe, Server } from "lucide-react"

export const categories = [
    { name: 'All', icon: <Globe className="w-5 h-5" /> },
    { name: 'Front-End', icon: <Code className="w-5 h-5" /> },
    { name: 'Back-End', icon: <Server className="w-5 h-5" /> },
    { name: 'Full Stack', icon: <Database className="w-5 h-5" /> },
    { name: 'Foundation', icon: <Cpu className="w-5 h-5" /> },
    { name: 'C', icon: 'C' },
    { name: 'C++', icon: 'C++' },
    { name: 'Java', icon: 'Java' },
    { name: 'Python', icon: 'Py' }
]

export const projects = [
    {
        id: 1,
        name: 'Responsive Portfolio',
        category: 'Front-End',
        group: 'Foundation',
        level: 'beginner',
        language: 'HTML/CSS',
        description: 'A personal portfolio website that adapts to various screen sizes, showcasing responsive design techniques.',
        features: ['Mobile-first design', 'Flexbox layout', 'CSS Grid', 'Media queries'],
        learningOutcomes: ['Understanding of responsive design principles', 'Proficiency in CSS layout techniques', 'Basic SEO optimization'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 2,
        name: 'Task Manager CLI',
        category: 'Back-End',
        group: 'Python',
        level: 'beginner',
        language: 'Python',
        description: 'A command-line interface application for managing tasks and to-do lists.',
        features: ['Add, remove, and mark tasks as complete', 'Save tasks to a file', 'List all tasks', 'Priority levels for tasks'],
        learningOutcomes: ['Basic Python programming', 'File I/O operations', 'Command-line argument parsing', 'Data structures in Python'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 3,
        name: 'Weather Dashboard',
        category: 'Front-End',
        group: 'JavaScript',
        level: 'intermediate',
        language: 'JavaScript/API',
        description: 'An interactive weather dashboard that displays current weather and forecasts for multiple cities.',
        features: ['API integration', 'Dynamic UI updates', 'Local storage for saved cities', 'Responsive design'],
        learningOutcomes: ['Working with APIs', 'Asynchronous JavaScript', 'DOM manipulation', 'Local storage usage'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 4,
        name: 'Inventory Management System',
        category: 'Full Stack',
        group: 'Java',
        level: 'intermediate',
        language: 'Java/Spring Boot',
        description: 'A web-based inventory management system for small businesses.',
        features: ['CRUD operations for inventory items', 'User authentication', 'Reporting functionality', 'RESTful API'],
        learningOutcomes: ['Spring Boot framework', 'Database design and ORM', 'RESTful API development', 'Java web application architecture'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 5,
        name: 'Data Structures Library',
        category: 'Foundation',
        group: 'C++',
        level: 'intermediate',
        language: 'C++',
        description: 'A comprehensive library implementing various data structures in C++.',
        features: ['Linked lists', 'Trees (Binary, AVL, Red-Black)', 'Graphs', 'Hash tables'],
        learningOutcomes: ['Advanced C++ programming', 'Data structure implementation', 'Algorithm complexity analysis', 'Template metaprogramming'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 6,
        name: 'E-commerce Platform',
        category: 'Full Stack',
        group: 'JavaScript',
        level: 'advanced',
        language: 'React/Node.js',
        description: 'A full-featured e-commerce platform with user authentication, product catalog, and payment integration.',
        features: ['User authentication', 'Product search and filtering', 'Shopping cart', 'Payment gateway integration'],
        learningOutcomes: ['Full-stack JavaScript development', 'State management in React', 'RESTful API design', 'Database modeling'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 7,
        name: 'Compiler Design',
        category: 'Foundation',
        group: 'C',
        level: 'advanced',
        language: 'C',
        description: 'A basic compiler for a simple programming language, implemented in C.',
        features: ['Lexical analysis', 'Syntax parsing', 'Semantic analysis', 'Code generation'],
        learningOutcomes: ['Compiler theory and design', 'Advanced C programming', 'Formal language theory', 'Low-level code generation'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 8,
        name: 'Machine Learning Model Deployment',
        category: 'Back-End',
        group: 'Python',
        level: 'advanced',
        language: 'Python/Flask/TensorFlow',
        description: 'A web service that deploys a pre-trained machine learning model for real-time predictions.',
        features: ['RESTful API for predictions', 'Model versioning', 'Input validation', 'Scalable architecture'],
        learningOutcomes: ['Machine learning deployment strategies', 'Web service development with Flask', 'API design for ML models', 'Scalability in ML applications'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 9,
        name: 'Distributed Key-Value Store',
        category: 'Back-End',
        group: 'Java',
        level: 'advanced',
        language: 'Java',
        description: 'A distributed key-value store with support for replication and partitioning.',
        features: ['Consistent hashing', 'Replication for fault tolerance', 'Partitioning for scalability', 'Gossip protocol for cluster membership'],
        learningOutcomes: ['Distributed systems design', 'Network programming in Java', 'Consistency models in distributed databases', 'Fault tolerance strategies'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
    {
        id: 10,
        name: 'Real-time Collaborative Editor',
        category: 'Full Stack',
        group: 'JavaScript',
        level: 'advanced',
        language: 'React/Node.js/WebSocket',
        description: 'A web-based collaborative text editor supporting real-time editing by multiple users.',
        features: ['Real-time synchronization', 'Operational transformation', 'Presence awareness', 'Version history'],
        learningOutcomes: ['Real-time web technologies', 'Conflict resolution in distributed systems', 'Scalable WebSocket architectures', 'Advanced state management in React'],
        desktopImage: '/placeholder.svg?height=300&width=400',
        mobileImage: '/placeholder.svg?height=400&width=200',
    },
]